package uvg.edu.gt.smartfridge.ui.theme

import androidx.compose.material.Colors
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

// App Color palette.

val md_theme_light_primary = Color(0xFF48BE6B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA0DBB3)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFFFFBF73)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFFFFDF9D)
val md_theme_light_onSecondaryContainer = Color(0xFF000000)
val md_theme_light_tertiary = Color(0xFF00639C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCEE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D33)
val md_theme_light_error = Color(0xFFE34A3D)
val md_theme_light_errorContainer = Color(0xFFE34A3D)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF7F8FA)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF7F8FA)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFFC4C4C4)
val md_theme_light_inverseOnSurface = Color(0xFFFFFFFF)
val md_theme_light_inverseSurface = Color(0xFF000000)
val md_theme_light_inversePrimary = Color(0xFF69DD86)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D32)
val md_theme_light_outlineVariant = Color(0xFF878B85)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF337045)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF48BE6B)
val md_theme_dark_onPrimaryContainer = Color(0xFF000000)
val md_theme_dark_secondary = Color(0xFFFFBF73)
val md_theme_dark_onSecondary = Color(0xFF000000)
val md_theme_dark_secondaryContainer = Color(0xFFFFDF9D)
val md_theme_dark_onSecondaryContainer = Color(0xFF000000)
val md_theme_dark_tertiary = Color(0xFF97CBFF)
val md_theme_dark_onTertiary = Color(0xFF003354)
val md_theme_dark_tertiaryContainer = Color(0xFF004A77)
val md_theme_dark_onTertiaryContainer = Color(0xFFCEE5FF)
val md_theme_dark_error = Color(0xFFE34A3D)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2B2B2B)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF2B2B2B)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val md_theme_dark_outline = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface = Color(0xFFF7F8FA)
val md_theme_dark_inverseSurface = Color(0xFF000000)
val md_theme_dark_inversePrimary = Color(0xFF006D32)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF69DD86)
val md_theme_dark_outlineVariant = Color(0xFFAFB9AC)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF48BE6B)